NUMPY AND PANDAS

Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)

In [ ]:
import numpy as np

arr = np.arange(1, 11)
x = arr.reshape(2, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index. (Score:1)

In [ ]:
import numpy as np

arr = np.arange(1, 21)

extracted_elements = arr[4:15]

print("Original array:", arr)
print("Extracted elements (from 5th to 15th index):", extracted_elements)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Extracted elements (from 5th to 15th index): [ 5  6  7  8  9 10 11 12 13 14 15]


How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above (Score 1)

In [ ]:
import numpy as np
my_array = np.array([1, 5, 2, 8, 3, 9, 4, 7, 6,7,8,9,10])
mean_value = np.mean(my_array)
print(f"Mean: {mean_value}")

Mean: 6.076923076923077


In [ ]:
import numpy as np
my_array = np.array([1, 5, 2, 8, 3, 9, 4, 7, 6,7,8,9,10])
median_value = np.median(my_array)
print(f"Median: {median_value}")

Median: 7.0


In [ ]:
import numpy as np
my_array = np.array([1, 5, 2, 8, 3, 9, 4, 7, 6,7,8,9,10])
std_dev_value = np.std(my_array)
print(f"Standard Deviation: {std_dev_value}")

Standard Deviation: 2.7585263195447856


Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)  

In [ ]:
import numpy as np

x = np.array([[10, 20, 30, 40],
              [11, 21, 31, 41],
              [12, 22, 32, 42]])

y = np.array([1, 2, 3, 4])
result = x - y

print("Original 2D array x:")
print(x)
print("\nOriginal 1D array y:")
print(y)
print("\nResult of x - y (broadcasting):")
print(result)

Original 2D array x:
[[10 20 30 40]
 [11 21 31 41]
 [12 22 32 42]]

Original 1D array y:
[1 2 3 4]

Result of x - y (broadcasting):
[[ 9 18 27 36]
 [10 19 28 37]
 [11 20 29 38]]


Create a dataframe with the following columns: name, age, and gender. The dataframe
should have 10 rows of data. (Score: 2)
1) Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe. (Score: 1)
2) Select the rows of the dataframe where the age is greater than or equal to 30.
(Score: 1)
3) Convert this dataframe to a CSV file and read that CSV file, and finally display
the contents. (Score: 1)

Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [ ]:
import pandas as pd
data = {
    'name': ['Vinodkumar','Manoj','Navya','Saritha', 'Sandhya', 'Madhusoothanan', 'Bhavani', 'Nirmala', 'Sunilkumar', 'Mayadevi'],
    'age': [24, 30, 22, 28, 35, 31, 29, 21, 33, 27],
    'gender': ['Male', 'Male', 'Female', 'Female', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female']
}
df = pd.DataFrame(data)
print(df)

             name  age  gender
0      Vinodkumar   24    Male
1           Manoj   30    Male
2           Navya   22  Female
3         Saritha   28  Female
4         Sandhya   35  Female
5  Madhusoothanan   31    Male
6         Bhavani   29  Female
7         Nirmala   21  Female
8      Sunilkumar   33    Male
9        Mayadevi   27  Female


Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe. (Score: 1)

In [ ]:
occupations = ['Managing_Director','Purchase_cum_Sales_Manager','Computer_Programmer','Sales_Staff1', 'Sales_Staff2', 'Sales_Staff3', 'Sales_Staff4','Sales_Staff5', 'Sales_Staff6', 'Sales_Staff7']
df['occupation'] = occupations

print(df)

             name  age  gender                  occupation
0      Vinodkumar   24    Male           Managing_Director
1           Manoj   30    Male  Purchase_cum_Sales_Manager
2           Navya   22  Female         Computer_Programmer
3         Saritha   28  Female                Sales_Staff1
4         Sandhya   35  Female                Sales_Staff2
5  Madhusoothanan   31    Male                Sales_Staff3
6         Bhavani   29  Female                Sales_Staff4
7         Nirmala   21  Female                Sales_Staff5
8      Sunilkumar   33    Male                Sales_Staff6
9        Mayadevi   27  Female                Sales_Staff7


Select the rows of the dataframe where the age is greater than or equal to 30. (Score: 1)

In [ ]:
 import pandas as pd
data = {
    'name': ['Vinodkumar','Manoj','Navya','Saritha', 'Sandhya', 'Madhusoothanan', 'Bhavani', 'Nirmala', 'Sunilkumar', 'Mayadevi'],
    'age': [24, 30, 22, 28, 35, 31, 29, 21, 33, 27],
    'gender': ['Male', 'Male', 'Female', 'Female', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female']
}
df = pd.DataFrame(data)
occupations = ['Managing_Director','Purchase_cum_Sales_Manager','Computer_Programmer','Sales_Staff1', 'Sales_Staff2', 'Sales_Staff3', 'Sales_Staff4','Sales_Staff5', 'Sales_Staff6', 'Sales_Staff7']
df['occupation'] = occupations
#Select rows where age is greater than or equal to 30
df_filtered_age = df[df['age'] >= 30]
print("Original DataFrame with 'occupation' column:")
print(df)
print("\nDataFrame with rows where age is >= 30:")
print(df_filtered_age)

Original DataFrame with 'occupation' column:
             name  age  gender                  occupation
0      Vinodkumar   24    Male           Managing_Director
1           Manoj   30    Male  Purchase_cum_Sales_Manager
2           Navya   22  Female         Computer_Programmer
3         Saritha   28  Female                Sales_Staff1
4         Sandhya   35  Female                Sales_Staff2
5  Madhusoothanan   31    Male                Sales_Staff3
6         Bhavani   29  Female                Sales_Staff4
7         Nirmala   21  Female                Sales_Staff5
8      Sunilkumar   33    Male                Sales_Staff6
9        Mayadevi   27  Female                Sales_Staff7

DataFrame with rows where age is >= 30:
             name  age  gender                  occupation
1           Manoj   30    Male  Purchase_cum_Sales_Manager
4         Sandhya   35  Female                Sales_Staff2
5  Madhusoothanan   31    Male                Sales_Staff3
8      Sunilkumar   33    Mal

Convert this dataframe to a CSV file and read that CSV file, and finally display the contents.

In [5]:
 import pandas as pd
data = {
    'name': ['Vinodkumar','Manoj','Navya','Saritha', 'Sandhya', 'Madhusoothanan', 'Bhavani', 'Nirmala', 'Sunilkumar', 'Mayadevi'],
    'age': [24, 30, 22, 28, 35, 31, 29, 21, 33, 27],
    'gender': ['Male', 'Male', 'Female', 'Female', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female']
}
df = pd.DataFrame(data)
occupations = ['Managing_Director','Purchase_cum_Sales_Manager','Computer_Programmer','Sales_Staff1', 'Sales_Staff2', 'Sales_Staff3', 'Sales_Staff4','Sales_Staff5', 'Sales_Staff6', 'Sales_Staff7']
df['occupation'] = occupations
#Select rows where age is greater than or equal to 30
df_filtered_age = df[df['age'] >= 30]
print("Original DataFrame with 'occupation' column:")
print(df)
print("\nDataFrame with rows where age is >= 30:")
print(df_filtered_age)

# Convert the filtered DataFrame to a CSV file
data = df.csv'
df_filtered.to_csv(data, index=False)
print(f"DataFrame saved to '{data}'")
print("\n")

#  Read the CSV file and display its contents
df_from_csv = pd.read_csv(data)
print(f"Contents of '{data}' after reading:")
print(df_from_csv)

SyntaxError: unterminated string literal (detected at line 18) (ipython-input-2615607214.py, line 18)