Linear Algebra and Probability
In this assignment, you will apply Linear Algebra and Probability techniques to analyze the Wine
Quality Dataset. The dataset consists of 1599 rows and 12 columns, detailing various chemical
properties of red and white wines and their quality scores. Your tasks will focus on vectors,
matrices, eigenvalues, eigenvectors, and basic probability concepts. You can download the
dataset from the link given below.  The dataset contains 1599 samples of wine, with features
such as acidity, alcohol content, pH, residual sugar, and others, alongside the target variable,
wine quality.  
1. Load the dataset and handle any missing data by replacing null values with the mean
value of the respective column. (Score 2)
2. Extract the following columns as vectors: alcohol,citric acid. (Score 2)
3. Select two features (e.g., alcohol and density) from the dataset and calculate the
covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the
selected columns.(Score 2)
4. Perform eigen decomposition on the covariance matrix you computed in question 3.
Identify and interpret the results:Identify the top 2 eigenvalues of the covariance
matrix,Identify the corresponding eigenvectors.(Score 2)
5. Which wine quality is most common in the dataset? How can you interpret the
distribution of wine quality scores? (Score 2)
https://drive.google.com/file/d/1OnJ8qjX8HAlNU5JCHFRdYjMHLd78Ft56/view?usp=drive_link

In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5


Load the dataset and handle any missing data by replacing null values with the mean value of the respective column. (Score 2)

In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import numpy as np
df.info()
# Identify numerical columns
numerical_cols = df.select_dtypes(include=np.number).columns

# Fill missing values in each numerical column with its mean
for col in numerical_cols:
    if df[col].isnull().any(): # Check if the column actually has missing values
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['fixed acidity']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)


The mean is: 8.31963727329581


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['volatile acidity']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)


The mean is: 0.5278205128205128


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['citric acid']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 0.2709756097560976


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['residual sugar']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 2.53880550343965


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['chlorides']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 0.0874665415884928


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['free sulfur dioxide']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 15.874921826141339


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['total sulfur dioxide']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 46.46779237023139


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['density']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 0.996746679174484


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['pH']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 3.311113195747342


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['sulphates']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 0.6581488430268918


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['alcohol']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 10.422983114446529


In [ ]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
df
import statistics
data = df['quality']
mean_value = statistics.mean(data)
print("The mean is:", mean_value)

The mean is: 5.6360225140712945


Extract the following columns as vectors: alcohol,citric acid. (Score 2)

In [ ]:
import numpy as np

# Define two vectors
v1 = np.array(df['alcohol'])
v2 = np.array( df['citric acid'])

# Vector Addition (element-wise)
addition = v1 + v2
print(f"Addition: {addition}")

# Scalar Multiplication
scalar = 3
mult = scalar * v1
print(f"Scalar Multiplication: {mult}")

# Dot Product (scalar result)
dot_product = np.dot(v1, v2)
print(f"Dot Product: {dot_product}")


# Magnitude of a vector
magnitude_v1 = np.linalg.norm(v1)
print(f"Magnitude of v1: {magnitude_v1}")

Addition: [ 9.4   9.8   9.84 ... 11.13 10.32 11.47]
Scalar Multiplication: [28.2 29.4 29.4 ... 33.  30.6 33. ]
Dot Product: 4552.6329999977615
Magnitude of v1: 418.96043866539156


Select two features (e.g., alcohol and density) from the dataset and calculate the covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the selected columns.(Score 2)

In [5]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
import numpy as np
selected_columns = ['alcohol', 'density']
X = df[selected_columns].values
cov_matrix = np.cov(X.T)
print("Covariance Matrix:")
print(cov_matrix)

Covariance Matrix:
[[ 1.13564740e+00 -9.97951790e-04]
 [-9.97951790e-04  3.56202945e-06]]


Perform eigen decomposition on the covariance matrix you computed in question 3. Identify and interpret the results:Identify the top 2 eigenvalues of the covariance matrix,Identify the corresponding eigenvectors.(Score 2)

In [9]:
import pandas as pd
df = pd.read_excel("Wine_Quality_red.xlsx")
import numpy as np

selected_columns = ['alcohol', 'density']
X = df[selected_columns].values
cov_matrix = np.cov(X.T)

eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

sorted_index = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_index]
sorted_eigenvectors = eigenvectors[:, sorted_index]

# Identify the top 2 eigenvalues and eigenvectors
# Assuming the matrix is at least 2x2
top_2_eigenvalues = sorted_eigenvalues[:2]
top_2_eigenvectors = sorted_eigenvectors[:, :2]

print("Covariance Matrix from Question 3:")
print(cov_matrix)
print(
"Eigenvalues (sorted descending):", sorted_eigenvalues)
print("Eigenvectors (sorted to match eigenvalues, columns):\n", sorted_eigenvectors)
print("\nTop 2 Eigenvalues:", top_2_eigenvalues)
print("Corresponding Top 2 Eigenvectors:\n", top_2_eigenvectors)



Covariance Matrix from Question 3:
[[ 1.13564740e+00 -9.97951790e-04]
 [-9.97951790e-04  3.56202945e-06]]
Eigenvalues (sorted descending): [1.13564827e+00 2.68507580e-06]
Eigenvectors (sorted to match eigenvalues, columns):
 [[-9.99999614e-01 -8.78753184e-04]
 [ 8.78753184e-04 -9.99999614e-01]]

Top 2 Eigenvalues: [1.13564827e+00 2.68507580e-06]
Corresponding Top 2 Eigenvectors:
 [[-9.99999614e-01 -8.78753184e-04]
 [ 8.78753184e-04 -9.99999614e-01]]


Which wine quality is most common in the dataset? How can you interpret the distribution of wine quality scores? (Score 2)